export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_PERMISSION = 'SET_PERMISSION';
// Timetable
export const TIMETABLE_ORDER_ADD = ' TIMETABLE_ORDER_ADD';
export const TIMETABLE_ORDER_MOVE = ' TIMETABLE_ORDER_MOVE';
export const TIMETABLE_ORDER_REMOVE = ' TIMETABLE_ORDER_REMOVE';
export const UNSET_TIMETABLE_ACTIVE_DAY = ' UNSET_TIMETABLE_ACTIVE_DAY';
export const SET_TIMETABLE_ACTIVE_DAY = ' SET_TIMETABLE_ACTIVE_DAY';
export const SET_TIMETABLE_POSITIONS = ' SET_TIMETABLE_POSITIONS';
export const GET_TIMETABLE = ' GET_TIMETABLE';
export const GET_TIMETABLE_ERROR = 'GET_TIMETABLE_ERROR';
// Stats
export const SET_YEARS_CUSTOMER = 'SET_YEARS_CUSTOMER';
export const SET_ACTIVE_YEAR = 'SET_ACTIVE_YEAR';
export const SET_ACTIVE_POSITION_ON_PRODUCTION_STATS =
 'SET_ACTIVE_POSITION_ON_PRODUCTION_STATS';
export const GET_PRODUCTION_STATS_YEARS = 'GET_PRODUCTION_STATS_YEARS';
export const GET_PRODUCTION_STATS_YEARS_ERROR =
 'GET_PRODUCTION_STATS_YEARS_ERROR';
export const SET_ACTIVE_MONTH = 'SET_ACTIVE_MONTH';
export const SET_ACTIVE_DAY = 'SET_ACTIVE_DAY';
export const SET_ACTIVE_EMPLOYEE = 'SET_ACTIVE_EMPLOYEE';
export const SET_ACTIVE_CUSTOMER = 'SET_ACTIVE_CUSTOMER';
export const GET_PRODUCTION_STATS = 'GET_PRODUCTION_STATS';
export const GET_EMPLOYEE_STATS = 'GET_EMPLOYEE_STATS';
export const GET_EMPLOYEE_STATS_ERROR = 'GET_EMPLOYEE_STATS_ERROR';
export const GET_PRODUCTION_STATS_ERROR = 'GET_PRODUCTION_STATS_ERROR';
// Orders
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const CUSTOMER_ORDERS_IN_PROD = 'CUSTOMER_ORDERS_IN_PROD';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const ORDERS_LOAD_REQUEST = 'ORDERS_LOAD_REQUEST';
export const ORDERS_LOADED = 'ORDERS_LOADED';
export const ORDERS_LOADED_ERROR = 'ORDERS_LOADED_ERROR';
export const SEARCH_ORDER = 'SEARCH_ORDER';
// Employees
export const GET_POSITION_ORDERS = 'GET_POSITION_ORDERS';
export const SET_POSITION_ACTIVE_ORDERS = 'SET_POSITION_ACTIVE_ORDERS';
export const GET_POSITION_ORDERS_ERROR = 'GET_POSITION_ORDERS_ERROR';
export const GET_POSITION_EMPLOYEES = 'GET_POSITION_EMPLOYEES';
export const GET_POSITION_EMPLOYEES_ERROR = 'GET_POSITION_EMPLOYEES_ERROR';
export const SET_ACTIVE_POSITION = 'SET_ACTIVE_POSITION';
export const SET_EMPLOYEE_FILTER = 'SET_EMPLOYEE_FILTER';
export const CLEAR_EMPLOYEE_FILTER = 'CLEAR_EMPLOYEE_FILTER';
// BLOW
export const POSITIONS_LIST_LOADED = 'POSITIONS_LIST_LOADED,';
export const EMPLOYEES_LIST_LOADED = ' EMPLOYEES_LIST_LOADED,';
export const POSITIONS_LIST_ERROR = ' POSITIONS_LIST_ERROR,';
export const EMPLOYEES_LIST_ERROR = ' EMPLOYEES_LIST_ERROR';
export const EMPLOYEE__LOAD = 'EMPLOYEE__LOAD';
export const EMPLOYEE__LOAD__ERROR = 'EMPLOYEE__LOAD__ERROR';
// Messages
export const GET_MESSAGES = ' GET_MESSAGES';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';
// Production
export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
export const ORDERS_IN_PRODUCTION_LOADED = 'ORDERS_IN_PRODUCTION_LOADED';
export const ORDERS_IN_PRODUCTION_LOADED_ERROR =
 'ORDERS_IN_PRODUCTION_LOADED_ERROR';
export const SET_PRODUCTION_FILTER = 'SET_PRODUCTION_FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
// NewOrder
export const ADD_IMPORTED_ITEMS = 'ADD_IMPORTED_ITEMS';
export const SET_IMPORT_DATA_FILE = 'SET_IMPORT_DATA_FILE';
export const SET_REASON_OF_COMPLAINT = 'SET_REASON_OF_COMPLAINT';
export const SET_NUT = 'SET_NUT';
export const SET_FELC = 'SET_FELC';
export const SET_CHAMFERING = 'SET_CHAMFERING';
export const REMOVE_ORDER_IMAGES = 'REMOVE_ORDER_IMAGES';
export const ADD_ORDER_IMAGES = 'ADD_ORDER_IMAGES';
export const SET_ORDER_AS_DATA = 'SET_ORDER_AS_DATA';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const SET_ACTIVE_ORDER = 'SET_ACTIVE_ORDER';
export const SET_EDITED_ORDER = 'SET_EDITED_ORDER';
export const ADD_CUSTOM_MILLING = 'ADD_CUSTOM_MILLING';
export const ADD_TYPE = 'ADD_TYPE';
export const ADD_USER = 'ADD_USER';
export const ADD_IMAGE = 'ADD_IMAGE';
export const SET_ITEMS = 'SET_ITEMS';
export const SET_NUMBER_OF_ELEMENTS = 'SET_NUMBER_OF_ELEMENTS';
export const SET_NUMBER = 'SET_NUMBER';
export const ADD_PAINT_STYLE = 'ADD_PAINT_STYLE';
export const SET_PRICE = 'SET_PRICE';
export const CALCULATE_ORDER = 'CALCULATE_ORDER';
export const HANDLE_ITEM_DATA = 'HANDLE_ITEM_DATA';
export const HANDLE_NAME = 'HANDLE_NAME';
export const HANDLE_ORDER_COMMENTS = 'HANDLE_ORDER_COMMENTS';
export const ADD_ITEM = 'ADD_ITEM';
export const ADD_MILLING = 'ADD_MILLING';
export const ADD_GLASSCASE = 'ADD_GLASSCASE';
export const ADD_HANDLE = 'ADD_HANDLE';
export const ADD_COLOR = 'ADD_COLOR';
export const ADD_PAINT_TYPE = 'ADD_PAINT_TYPE';
export const ADD_VENEER = 'ADD_VENEER';
export const REMOVE_MILLING = 'REMOVE_MILLING';
export const REMOVE_GLASSCASE = 'REMOVE_GLASSCASE';
export const REMOVE_HANDLE1 = 'REMOVE_HANDLE1';
export const REMOVE_HANDLE2 = 'REMOVE_HANDLE2';
export const REMOVE_COLOR = 'REMOVE_COLOR';
export const REMOVE_VENEER = 'REMOVE_VENEER';
export const SET_CURRENT_DATE = 'SET_CURRENT_DATE';
export const SET_FINISH_DATE = 'SET_FINISH_DATE';
export const ADD_ORDER_ITEM = 'ADD_ORDER_ITEM';
export const REMOVE_ORDER_ITEM = 'REMOVE_ORDER_ITEM';
export const CLEAR_ORDER = 'CLEAR_ORDER';
// View
export const SET_SPINNER = 'SET_SPINNER';
export const SET_COMPONENT_IN_MODAL = 'SET_COMPONENT_IN_MODAL';
export const SET_MODEL_LEFT_SIDE = 'SET_MODEL_LEFT_SIDE';
export const SET_MODEL_RIGHT_SIDE = 'SET_MODEL_RIGHT_SIDE';
export const SET_POSITIONS_TO_DISPLAY = 'SET_POSITIONS_TO_DISPLAY';
export const SET_LISTELEMENTS_TO_DISPLAY = 'SET_LISTELEMENTS_TO_DISPLAY';
export const SET_DISPLAY_FROM_STORAGE = 'SET_DISPLAY_FROM_STORAGE';
export const SET_SORT = 'SET_SORT';
export const SET_ADMIN_HOME_PAGE_KEY = 'SET_ADMIN_HOME_PAGE_KEY';
export const SET_ENDED_ORDERS_DATE = 'SET_ENDED_ORDERS_DATE';
export const SET_ENDED_ORDERS_DATE_FROM = 'SET_ENDED_ORDERS_DATE_FROM';
export const SET_ITEM_TO_PREVIEW = 'SET_ITEM_TO_PREVIEW';
export const SET_EMPLOYEE_LIST_FILTER_BY = 'SET_EMPLOYEE_LIST_FILTER_BY';
// search
export const SET_HOME_SEARCH = 'SET_HOME_SEARCH';
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT';
export const SET_SEARCH_RESULT_ERROR = 'SET_SEARCH_RESULT_ERROR';
export const SET_SORT_SEARCH_LIST = 'SET_SORT_SEARCH_LIST';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_SEARCH_VALUES_EMPTY = 'SET_SEARCH_VALUES_EMPTY';
// Customers
export const CUSTOMERS_LIST_LOADED = 'CUSTOMERS_LIST_LOADED';
export const CUSTOMER_ORDERS_LOADED = 'CUSTOMER_ORDERS_LOADED';
export const CUSTOMER_DATA_LOADED = 'CUSTOMER_DATA_LOADED';
export const CUSTOMER_ORDERS_ERROR = 'CUSTOMER_ORDERS_ERROR';
export const CUSTOMER_DATA_ERROR = 'CUSTOMER_DATA_ERROR';
export const CUSTOMERS_LIST_ERROR = 'CUSTOMERS_LIST_ERROR';
export const GET_CUSTOMER_STATS = 'GET_CUSTOMER_STATS';
export const GET_CUSTOMER_STATS_ERROR = 'GET_CUSTOMER_STATS_ERROR';
// Prices
export const LOAD_PRICES = 'LOAD_PRICES';
export const LOAD_PRICES_ERROR = 'LOAD_PRICES_ERROR';
// Settings
export const LOAD_GLOBAL_SETTINGS = 'LOAD_GLOBAL_SETTINGS';
export const LOAD_GLOBAL_SETTINGS_ERROR = 'LOAD_GLOBAL_SETTINGS_ERROR';
// PaintsOrders
export const ADD_SKIPPED_ORDER = 'ADD_SKIPPED_ORDER';
export const REMOVE_SKIPPED_ORDER = 'REMOVE_SKIPPED_ORDER';
export const ADD_PAINTS_ORDER = 'ADD_PAINTS_ORDER';
export const SET_INITIAL_PAINTS_ORDERS = 'SET_INITIAL_PAINTS_ORDERS';
