/* eslint-disable import/prefer-default-export */
export const theme = {
 blowGreen: '#73a52e',
 blowGreenLight: '#cde7a9',
 blowPrimary: '#a4cfff',
 blowPrimaryLight: '#b1cff1',
 blowSuccess: '#85eb6a',
 blowSuccessLight: '#b9faa7',
 blowInfo: '#31b0c4',
 blowInfoLight: '#45c5d9',
 blowWarning: '#ffbd40',
 blowWarningLight: '#fcd7a0',
 blowDanger: '#fa3e54',
 blowDangerLight: '#e7bcba',
 blowDark: '#343a40',
 blowLightGrey: '#f5f5f5',
 blowPurple: '#e165b9',
 positions: {
  Surówka: '#ffbd40',
  Podkład: '#f5f5f5',
  Szlifiernia: '#33cec3',
  Lakiernia: '#a4cfff',
  Polernia: '#fa3e54',
  Pakowanie: '#85eb6a',
  Zakończone: '#e165b9',
  Transport: 'gray',
 },
};
